---

# https://github.com/wayofdev/gh-actions/blob/master/.github/workflows/create-release.yml
# https://github.com/google-github-actions/release-please-action#release-types-supported
# https://github.com/googleapis/release-please/blob/main/docs/customizing.md

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

name: ðŸ“¦ Create release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸŽ‰ Create release
        uses: googleapis/release-please-action@v4.1.1
        id: release
        with:
          token: ${{ secrets.TRAP_RELEASE_TOKEN }}
          config-file: .github/.release-please-config.json
          manifest-file: resources/version.json
          target-branch: master

...
